font_family              MonoLisa Static Nerd Font
bold_font                MonoLisa Static Nerd Font
italic_font              MonoLisa Static Nerd Font
bold_italic_font         MonoLisa Static Nerd Font
font_size                12
modify_font              cell_height 14px

window_padding_width     0 0 0 4
placement_strategy       center
confirm_os_window_close  0

cursor                   #a0adde
cursor_text_color        #1e1e2e
cursor_trail             10
cursor_trail_decay       0.01 0.05
cursor_trail_start_threshold  0

mouse_hide_wait          1
enable_audio_bell        no

foreground               #cdd6f4
background               #010515

selection_foreground     #1e1e2e
selection_background     #f5e0dc

color0                   #2b314f
color8                   #2b314f

color1                   #ea618f
color9                   #ea618f

color2                   #67e4bf
color10                  #67e4bf

color3                   #db9882
color11                  #db9882

color4                   #70a1eb
color12                  #70a1eb

color5                   #b882ed
color13                  #b882ed

color6                   #64aece
color14                  #64aece

color7                   #dee1e6
color15                  #233459

allow_remote_control yes
dynamic_background_opacity yes
map ctrl+shift+t set_background_opacity 0.6
map ctrl+shift+o set_background_opacity 1.0
