bind = Super, C, killactive,
bind = Super, V, togglefloating,
bind = Super, B, exec, kitty -e bluetoothctl
bind = Super, Q, exec, RAND=$RANDOM && kitty --listen-on unix:/tmp/kitty-$RAND -e tmux new-session "KITTY_LISTEN_ON=unix:/tmp/kitty-$RAND && zsh"
bind = Super, N, exec, RAND=$RANDOM && kitty --listen-on unix:/tmp/kitty-$RAND -e tmux new-session "KITTY_LISTEN_ON=unix:/tmp/kitty-$RAND && nvim"
bind = Super, F, exec, RAND=$RANDOM && kitty --listen-on unix:/tmp/kitty-$RAND -e tmux new-session "KITTY_LISTEN_ON=unix:/tmp/kitty-$RAND && zsh -i -c yazi"
bind = Super, grave, togglespecialworkspace
bind = Super Shift, grave, movetoworkspace, special
bind = Super, Backslash, resizeactive, exact 1000 500

bind = Super, S, exec, grim -g "$(slurp)" - | wl-copy
bind = Super, M, exec, ~/.config/hypr/scripts/move-to-empty-workspace
bind = Super, T, layoutmsg, togglesplit
bind = Super, SPACE, exec, wofi -I --show drun --normal-window
bind = Super, P, exec, ~/.config/hypr/scripts/powermenu/powermenu
bind = Super, Y, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next
bind = Super, I, exec, hyprlock
bind = Super, O, exec, ~/scripts/launch_obsidian

bind =,XF86AudioMute, exec, ~/.config/hypr/scripts/volume mute
binde =,XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volume down
binde =,xf86audioraisevolume, exec,~/.config/hypr/scripts/volume up
binde =,XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness down
binde =,XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness up
bind =,XF86AudioPlay, exec, playerctl play-pause
bind =,XF86AudioPrev, exec, playerctl previous
bind =,XF86AudioNext, exec, playerctl next

bind = SUPERSHIFT, C, exec, bash ~/.config/hypr/scripts/colorpicker

bind = Super, H, movefocus, l
bind = Super, J, movefocus, r
bind = Super, K, movefocus, u
bind = Super, L, movefocus, d

bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

bind = Super SHIFT, 1, movetoworkspace, 1
bind = Super SHIFT, 2, movetoworkspace, 2
bind = Super SHIFT, 3, movetoworkspace, 3
bind = Super SHIFT, 4, movetoworkspace, 4
bind = Super SHIFT, 5, movetoworkspace, 5
bind = Super SHIFT, 6, movetoworkspace, 6
bind = Super SHIFT, 7, movetoworkspace, 7
bind = Super SHIFT, 8, movetoworkspace, 8
bind = Super SHIFT, 9, movetoworkspace, 9
bind = Super SHIFT, 0, movetoworkspace, 10

bindm = Super, Z, movewindow
bindm = Super, A, resizewindow

bind = Super, mouse_down, workspace, e+1
bind = Super, mouse_up, workspace, e-1

bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

binde = Super, Semicolon, layoutmsg, splitratio -0.1
binde = Super, Apostrophe, layoutmsg, splitratio +0.1

bind = Super, e, hyprexpo:expo, toggle
