exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = $HOME/scripts/import_env tmux
exec-once=hyprpanel

exec-once=gsettings set org.gnome.desktop.interface gtk-theme 'Mojave-Dark'
exec-once=gsettings set org.gnome.desktop.interface icon-theme 'WhiteSur'
exec-once=gsettings set org.gnome.desktop.interface cursor-theme 'Breeze'
exec-once=gsettings set org.gnome.desktop.interface font-name 'SF Pro Text'
exec-once=gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

exec-once = hyprpm reload -n
