unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.config/tmux/tmux.conf
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins"

set-option -g renumber-windows on
set -g focus-events on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:RGB"
set -g allow-passthrough on

unbind %
bind | run-shell 'tmux split-window -h -c "$(~/.config/tmux/project-root.sh)"'

unbind '"'
bind - run-shell 'tmux split-window -v -c "$(~/.config/tmux/project-root.sh)"'

bind c run-shell 'tmux new-window -c "$(~/.config/tmux/project-root.sh)"'

set -ga terminal-overrides ",xterm-kitty:Tc"
set -g default-terminal "xterm-kitty"
set -g set-clipboard on
set-option -g destroy-unattached on

bind-key < swap-window -t -1 \; select-window -t -1
bind-key > swap-window -t +1 \; select-window -t +1

set -g mouse on
set -g base-index 1

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "aserowy/tmux.nvim"
set -g @plugin "christoomey/vim-tmux-navigator"

### THEME ###
set-option -g status-style bg=default,fg=white
set-option -g status-position bottom

# Left
set-window-option -g status-left ""

# Right
set-window-option -g status-right ""

# Center
set-window-option -g window-status-style fg=cyan,bg=default,dim
set-window-option -g window-status-current-style fg=#010515,bg=#92b2fe
set-window-option -g window-status-format "#[fg=#92b2fe]#W"
set-window-option -g window-status-current-format "#[fg=#92b2fe,bg=#010515,bold]#W"
set-window-option -g status-justify centre

set -g pane-border-style fg=#233459
set -g pane-active-border-style fg=#233459


# only show the status bar if there is more than one window
set -g status off
set-hook -g after-new-window      'if "[ #{session_windows} -gt 1 ]" "set status on"'
set-hook -g after-kill-pane       'if "[ #{session_windows} -lt 2 ]" "set status off"'
set-hook -g pane-exited           'if "[ #{session_windows} -lt 2 ]" "set status off"'
set-hook -g window-layout-changed 'if "[ #{session_windows} -lt 2 ]" "set status off"'

run "~/.tmux/plugins/tpm/tpm"
